import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'en',
        'ar',
        'fr',
        'id',
        'ja',
        'pt',
        'nl',
        'th',
        'vi',
        'uk',
        'ta',
        'de',
        'es',
        'hi',
        'it',
        'ko',
        'ru',
        'pl',
        'tr',
        'ro',
        'bn',
        'mr',
        'te'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? arText = '',
    String? frText = '',
    String? idText = '',
    String? jaText = '',
    String? ptText = '',
    String? nlText = '',
    String? thText = '',
    String? viText = '',
    String? ukText = '',
    String? taText = '',
    String? deText = '',
    String? esText = '',
    String? hiText = '',
    String? itText = '',
    String? koText = '',
    String? ruText = '',
    String? plText = '',
    String? trText = '',
    String? roText = '',
    String? bnText = '',
    String? mrText = '',
    String? teText = '',
  }) =>
      [
        enText,
        arText,
        frText,
        idText,
        jaText,
        ptText,
        nlText,
        thText,
        viText,
        ukText,
        taText,
        deText,
        esText,
        hiText,
        itText,
        koText,
        ruText,
        plText,
        trText,
        roText,
        bnText,
        mrText,
        teText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

/// Used if the locale is not supported by GlobalMaterialLocalizations.
class FallbackMaterialLocalizationDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const FallbackMaterialLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) async =>
      SynchronousFuture<MaterialLocalizations>(
        const DefaultMaterialLocalizations(),
      );

  @override
  bool shouldReload(FallbackMaterialLocalizationDelegate old) => false;
}

/// Used if the locale is not supported by GlobalCupertinoLocalizations.
class FallbackCupertinoLocalizationDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const FallbackCupertinoLocalizationDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      SynchronousFuture<CupertinoLocalizations>(
        const DefaultCupertinoLocalizations(),
      );

  @override
  bool shouldReload(FallbackCupertinoLocalizationDelegate old) => false;
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => _isSupportedLocale(locale);

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

bool _isSupportedLocale(Locale locale) {
  final language = locale.toString();
  return FFLocalizations.languages().contains(
    language.endsWith('_')
        ? language.substring(0, language.length - 1)
        : language,
  );
}

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    '435cpe01': {
      'en': 'Cycle',
      'ar': 'دورة',
      'bn': 'চক্র',
      'de': 'Zyklus',
      'es': 'Ciclo',
      'fr': 'Faire du vélo',
      'hi': 'चक्र',
      'id': 'Siklus',
      'it': 'Ciclo',
      'ja': 'サイクル',
      'ko': '주기',
      'mr': 'सायकल',
      'nl': 'Cyclus',
      'pl': 'Cykl',
      'pt': 'Ciclo',
      'ro': 'Ciclu',
      'ru': 'Цикл',
      'ta': 'மிதிவண்டி',
      'te': 'సైకిల్',
      'th': 'วงจร',
      'tr': 'Döngü',
      'uk': 'Цикл',
      'vi': 'Xe đạp',
    },
    'lj3a4ej5': {
      'en': 'Exercise',
      'ar': 'يمارس',
      'bn': 'ব্যায়াম',
      'de': 'Übung',
      'es': 'Ejercicio',
      'fr': 'Exercice',
      'hi': 'व्यायाम',
      'id': 'Latihan',
      'it': 'Esercizio',
      'ja': 'エクササイズ',
      'ko': '운동',
      'mr': 'व्यायाम',
      'nl': 'Oefening',
      'pl': 'Ćwiczenia',
      'pt': 'Exercício',
      'ro': 'Exercita',
      'ru': 'Упражнение',
      'ta': 'உடற்பயிற்சி',
      'te': 'వ్యాయామం',
      'th': 'ออกกำลังกาย',
      'tr': 'Egzersiz yapmak',
      'uk': 'Вправа',
      'vi': 'Bài tập',
    },
    'uazhgbe5': {
      'en': '+ 5',
      'ar': '+ 5',
      'bn': '+ ৫',
      'de': '+ 5',
      'es': '+ 5',
      'fr': '+ 5',
      'hi': '+ 5',
      'id': '+ 5',
      'it': '+ 5',
      'ja': '+ 5',
      'ko': '+ 5',
      'mr': '+ ५',
      'nl': '+ 5',
      'pl': '+ 5',
      'pt': '+ 5',
      'ro': '+ 5',
      'ru': '+ 5',
      'ta': '+ 5',
      'te': '+ 5',
      'th': '+ 5',
      'tr': '+ 5',
      'uk': '+ 5',
      'vi': '+ 5',
    },
    'fyhvvz6k': {
      'en': '- 5',
      'ar': '- 5',
      'bn': '- ৫',
      'de': '- 5',
      'es': '- 5',
      'fr': '- 5',
      'hi': '- 5',
      'id': '- 5',
      'it': '- 5',
      'ja': '- 5',
      'ko': '- 5',
      'mr': '- ५',
      'nl': '- 5',
      'pl': '- 5',
      'pt': '- 5',
      'ro': '- 5',
      'ru': '- 5',
      'ta': '- 5',
      'te': '- 5',
      'th': '- 5',
      'tr': '- 5',
      'uk': '- 5',
      'vi': '- 5',
    },
    'wj661xhg': {
      'en': 'Remaining',
      'ar': 'متبقي',
      'bn': 'অবশিষ্ট',
      'de': 'Übrig',
      'es': 'Restante',
      'fr': 'Restant',
      'hi': 'शेष',
      'id': 'Tersisa',
      'it': 'Rimanente',
      'ja': '残り',
      'ko': '남은',
      'mr': 'उर्वरित',
      'nl': 'Overig',
      'pl': 'Pozostały',
      'pt': 'Restante',
      'ro': 'Rămas',
      'ru': 'Оставшийся',
      'ta': 'மீதமுள்ளவை',
      'te': 'మిగిలినవి',
      'th': 'ที่เหลืออยู่',
      'tr': 'Geriye kalan',
      'uk': 'Залишок',
      'vi': 'Còn lại',
    },
    '2thazfj5': {
      'en': ' ',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'vh31iews': {
      'en': 'Loading sounds',
      'ar': 'تحميل الأصوات',
      'bn': 'শব্দ লোড হচ্ছে',
      'de': 'Sounds werden geladen',
      'es': 'Sonidos de carga',
      'fr': 'Chargement des sons',
      'hi': 'ध्वनियाँ लोड हो रही हैं',
      'id': 'Memuat suara',
      'it': 'Caricamento dei suoni',
      'ja': 'サウンドを読み込んでいます',
      'ko': '로딩 사운드',
      'mr': 'ध्वनी लोड होत आहे',
      'nl': 'Geluiden laden',
      'pl': 'Ładowanie dźwięków',
      'pt': 'Sons de carregamento',
      'ro': 'Se încarcă sunetele',
      'ru': 'Звуки загрузки',
      'ta': 'ஒலிகளை ஏற்றுகிறது',
      'te': 'శబ్దాలు లోడ్ అవుతున్నాయి',
      'th': 'กำลังโหลดเสียง',
      'tr': 'Yükleniyor sesleri',
      'uk': 'Звуки завантаження',
      'vi': 'Đang tải âm thanh',
    },
    '976ih78c': {
      'en': 'Readay to play',
      'ar': 'جاهز للعب',
      'bn': 'খেলার জন্য প্রস্তুত',
      'de': 'Spielbereit',
      'es': 'Listo para jugar',
      'fr': 'Prêt à jouer',
      'hi': 'खेलने के लिए तैयार',
      'id': 'Siap untuk bermain',
      'it': 'Pronto per giocare',
      'ja': 'プレイ準備完了',
      'ko': '플레이 준비 완료',
      'mr': 'खेळायला तयार',
      'nl': 'Klaar om te spelen',
      'pl': 'Gotowy do gry',
      'pt': 'Pronto para jogar',
      'ro': 'Gata de joc',
      'ru': 'Готов к игре',
      'ta': 'விளையாடத் தயாராகுங்கள்',
      'te': 'ఆడటానికి సిద్ధంగా ఉండండి',
      'th': 'พร้อมที่จะเล่น',
      'tr': 'Oynamaya hazır',
      'uk': 'День готовий до гри',
      'vi': 'Sẵn sàng để chơi',
    },
    'tcvbp3to': {
      'en': 'AI Coach',
      'ar': 'مدرب الذكاء الاصطناعي',
      'bn': 'এআই কোচ',
      'de': 'KI-Coach',
      'es': 'Entrenador de IA',
      'fr': 'Coach IA',
      'hi': 'एआई कोच',
      'id': 'Pelatih AI',
      'it': 'Allenatore di intelligenza artificiale',
      'ja': 'AIコーチ',
      'ko': 'AI 코치',
      'mr': 'एआय कोच',
      'nl': 'AI-coach',
      'pl': 'Trener AI',
      'pt': 'Treinador de IA',
      'ro': 'Antrenor de inteligență artificială',
      'ru': 'Тренер ИИ',
      'ta': 'AI பயிற்சியாளர்',
      'te': 'AI కోచ్',
      'th': 'โค้ช AI',
      'tr': 'Yapay Zeka Koçu',
      'uk': 'Тренер зі штучного інтелекту',
      'vi': 'Huấn luyện viên AI',
    },
    'yuxltmzy': {
      'en': 'Home',
      'ar': 'بيت',
      'bn': 'হোম',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'mr': 'मुखपृष्ठ',
      'nl': 'Thuis',
      'pl': 'Dom',
      'pt': 'Lar',
      'ro': 'Acasă',
      'ru': 'Дом',
      'ta': 'முகப்புப் பக்கம்',
      'te': 'హొమ్ పేజ్',
      'th': 'บ้าน',
      'tr': 'Ev',
      'uk': 'Дім',
      'vi': 'Trang chủ',
    },
  },
  // WorkoutPage
  {
    'zu56ndki': {
      'en': 'Workout name',
      'ar': 'اسم التمرين',
      'bn': 'ওয়ার্কআউটের নাম',
      'de': 'Trainingsname',
      'es': 'Nombre del entrenamiento',
      'fr': 'Nom de l\'entraînement',
      'hi': 'वर्कआउट का नाम',
      'id': 'Nama latihan',
      'it': 'Nome dell\'allenamento',
      'ja': 'ワークアウト名',
      'ko': '운동 이름',
      'mr': 'व्यायामाचे नाव',
      'nl': 'Naam van de training',
      'pl': 'Nazwa treningu',
      'pt': 'Nome do treino',
      'ro': 'Numele antrenamentului',
      'ru': 'Название тренировки',
      'ta': 'உடற்பயிற்சி பெயர்',
      'te': 'వ్యాయామ పేరు',
      'th': 'ชื่อการออกกำลังกาย',
      'tr': 'Antrenman adı',
      'uk': 'Назва тренування',
      'vi': 'Tên bài tập',
    },
    'jdw1sq1f': {
      'en': 'Number of cycles',
      'ar': 'عدد الدورات',
      'bn': 'চক্রের সংখ্যা',
      'de': 'Anzahl der Zyklen',
      'es': 'Número de ciclos',
      'fr': 'Nombre de cycles',
      'hi': 'चक्रों की संख्या',
      'id': 'Jumlah siklus',
      'it': 'Numero di cicli',
      'ja': 'サイクル数',
      'ko': '사이클 수',
      'mr': 'चक्रांची संख्या',
      'nl': 'Aantal cycli',
      'pl': 'Liczba cykli',
      'pt': 'Número de ciclos',
      'ro': 'Număr de cicluri',
      'ru': 'Количество циклов',
      'ta': 'சுழற்சிகளின் எண்ணிக்கை',
      'te': 'చక్రాల సంఖ్య',
      'th': 'จำนวนรอบ',
      'tr': 'Döngü sayısı',
      'uk': 'Кількість циклів',
      'vi': 'Số chu kỳ',
    },
    'ew951ie3': {
      'en': '5',
      'ar': '5',
      'bn': '৫',
      'de': '5',
      'es': '5',
      'fr': '5',
      'hi': '5',
      'id': '5',
      'it': '5',
      'ja': '5',
      'ko': '5',
      'mr': '५',
      'nl': '5',
      'pl': '5',
      'pt': '5',
      'ro': '5',
      'ru': '5',
      'ta': '5',
      'te': '5',
      'th': '5',
      'tr': '5',
      'uk': '5',
      'vi': '5',
    },
    '4ks5blo7': {
      'en': 'Number of exercises',
      'ar': 'عدد التمارين',
      'bn': 'ব্যায়ামের সংখ্যা',
      'de': 'Anzahl der Übungen',
      'es': 'Número de ejercicios',
      'fr': 'Nombre d\'exercices',
      'hi': 'अभ्यासों की संख्या',
      'id': 'Jumlah latihan',
      'it': 'Numero di esercizi',
      'ja': '練習回数',
      'ko': '운동 횟수',
      'mr': 'व्यायामांची संख्या',
      'nl': 'Aantal oefeningen',
      'pl': 'Liczba ćwiczeń',
      'pt': 'Número de exercícios',
      'ro': 'Numărul de exerciții',
      'ru': 'Количество упражнений',
      'ta': 'பயிற்சிகளின் எண்ணிக்கை',
      'te': 'వ్యాయామాల సంఖ్య',
      'th': 'จำนวนครั้งของการออกกำลังกาย',
      'tr': 'Egzersiz sayısı',
      'uk': 'Кількість вправ',
      'vi': 'Số lượng bài tập',
    },
    'xpm8xjy7': {
      'en': '5',
      'ar': '5',
      'bn': '৫',
      'de': '5',
      'es': '5',
      'fr': '5',
      'hi': '5',
      'id': '5',
      'it': '5',
      'ja': '5',
      'ko': '5',
      'mr': '५',
      'nl': '5',
      'pl': '5',
      'pt': '5',
      'ro': '5',
      'ru': '5',
      'ta': '5',
      'te': '5',
      'th': '5',
      'tr': '5',
      'uk': '5',
      'vi': '5',
    },
    'es7gt6nt': {
      'en': 'Exercise Duration',
      'ar': 'مدة التمرين',
      'bn': 'ব্যায়ামের সময়কাল',
      'de': 'Trainingsdauer',
      'es': 'Duración del ejercicio',
      'fr': 'Durée de l\'exercice',
      'hi': 'व्यायाम की अवधि',
      'id': 'Durasi Latihan',
      'it': 'Durata dell\'esercizio',
      'ja': '運動時間',
      'ko': '운동 시간',
      'mr': 'व्यायामाचा कालावधी',
      'nl': 'Oefeningsduur',
      'pl': 'Czas trwania ćwiczeń',
      'pt': 'Duração do exercício',
      'ro': 'Durata exercițiului',
      'ru': 'Продолжительность упражнения',
      'ta': 'உடற்பயிற்சி கால அளவு',
      'te': 'వ్యాయామ వ్యవధి',
      'th': 'ระยะเวลาการออกกำลังกาย',
      'tr': 'Egzersiz Süresi',
      'uk': 'Тривалість вправи',
      'vi': 'Thời lượng tập luyện',
    },
    '6aak1g8d': {
      'en': 'TextField',
      'ar': 'حقل النص',
      'bn': 'টেক্সটফিল্ড',
      'de': 'Textfeld',
      'es': 'Campo de texto',
      'fr': 'Champ de texte',
      'hi': 'पाठ्य से भरा',
      'id': 'Bidang Teks',
      'it': 'Campo di testo',
      'ja': 'テキストフィールド',
      'ko': '텍스트필드',
      'mr': 'मजकूर फील्ड',
      'nl': 'Tekstveld',
      'pl': 'Pole tekstowe',
      'pt': 'Campo de texto',
      'ro': 'Câmp de text',
      'ru': 'Текстовое поле',
      'ta': 'உரைப்புலம்',
      'te': 'టెక్స్ట్ ఫీల్డ్',
      'th': 'ฟิลด์ข้อความ',
      'tr': 'Metin Alanı',
      'uk': 'Текстове поле',
      'vi': 'Trường văn bản',
    },
    'yt1rdxnt': {
      'en': ':',
      'ar': ':',
      'bn': ':',
      'de': ':',
      'es': ':',
      'fr': ':',
      'hi': ':',
      'id': ':',
      'it': ':',
      'ja': '：',
      'ko': ':',
      'mr': ':',
      'nl': ':',
      'pl': ':',
      'pt': ':',
      'ro': ':',
      'ru': ':',
      'ta': ':',
      'te': ':',
      'th': '-',
      'tr': ':',
      'uk': ':',
      'vi': ':',
    },
    'tra4dit3': {
      'en': 'TextField',
      'ar': 'حقل النص',
      'bn': 'টেক্সটফিল্ড',
      'de': 'Textfeld',
      'es': 'Campo de texto',
      'fr': 'Champ de texte',
      'hi': 'पाठ्य से भरा',
      'id': 'Bidang Teks',
      'it': 'Campo di testo',
      'ja': 'テキストフィールド',
      'ko': '텍스트필드',
      'mr': 'मजकूर फील्ड',
      'nl': 'Tekstveld',
      'pl': 'Pole tekstowe',
      'pt': 'Campo de texto',
      'ro': 'Câmp de text',
      'ru': 'Текстовое поле',
      'ta': 'உரைப்புலம்',
      'te': 'టెక్స్ట్ ఫీల్డ్',
      'th': 'ฟิลด์ข้อความ',
      'tr': 'Metin Alanı',
      'uk': 'Текстове поле',
      'vi': 'Trường văn bản',
    },
    'fqe8s1wa': {
      'en': 'Rest Duration',
      'ar': 'مدة الراحة',
      'bn': 'বিশ্রামের সময়কাল',
      'de': 'Ruhedauer',
      'es': 'Duración del descanso',
      'fr': 'Durée du repos',
      'hi': 'आराम की अवधि',
      'id': 'Durasi Istirahat',
      'it': 'Durata del riposo',
      'ja': '休憩時間',
      'ko': '휴식 시간',
      'mr': 'विश्रांतीचा कालावधी',
      'nl': 'Rustduur',
      'pl': 'Czas odpoczynku',
      'pt': 'Duração do descanso',
      'ro': 'Durata odihnei',
      'ru': 'Продолжительность отдыха',
      'ta': 'ஓய்வு காலம்',
      'te': 'విశ్రాంతి వ్యవధి',
      'th': 'ระยะเวลาพักผ่อน',
      'tr': 'Dinlenme Süresi',
      'uk': 'Тривалість відпочинку',
      'vi': 'Thời gian nghỉ ngơi',
    },
    'wncgioqf': {
      'en': 'TextField',
      'ar': 'حقل النص',
      'bn': 'টেক্সটফিল্ড',
      'de': 'Textfeld',
      'es': 'Campo de texto',
      'fr': 'Champ de texte',
      'hi': 'पाठ्य से भरा',
      'id': 'Bidang Teks',
      'it': 'Campo di testo',
      'ja': 'テキストフィールド',
      'ko': '텍스트필드',
      'mr': 'मजकूर फील्ड',
      'nl': 'Tekstveld',
      'pl': 'Pole tekstowe',
      'pt': 'Campo de texto',
      'ro': 'Câmp de text',
      'ru': 'Текстовое поле',
      'ta': 'உரைப்புலம்',
      'te': 'టెక్స్ట్ ఫీల్డ్',
      'th': 'ฟิลด์ข้อความ',
      'tr': 'Metin Alanı',
      'uk': 'Текстове поле',
      'vi': 'Trường văn bản',
    },
    'uxe57nlt': {
      'en': ':',
      'ar': ':',
      'bn': ':',
      'de': ':',
      'es': ':',
      'fr': ':',
      'hi': ':',
      'id': ':',
      'it': ':',
      'ja': '：',
      'ko': ':',
      'mr': ':',
      'nl': ':',
      'pl': ':',
      'pt': ':',
      'ro': ':',
      'ru': ':',
      'ta': ':',
      'te': ':',
      'th': '-',
      'tr': ':',
      'uk': ':',
      'vi': ':',
    },
    '8fnm31g6': {
      'en': 'TextField',
      'ar': 'حقل النص',
      'bn': 'টেক্সটফিল্ড',
      'de': 'Textfeld',
      'es': 'Campo de texto',
      'fr': 'Champ de texte',
      'hi': 'पाठ्य से भरा',
      'id': 'Bidang Teks',
      'it': 'Campo di testo',
      'ja': 'テキストフィールド',
      'ko': '텍스트필드',
      'mr': 'मजकूर फील्ड',
      'nl': 'Tekstveld',
      'pl': 'Pole tekstowe',
      'pt': 'Campo de texto',
      'ro': 'Câmp de text',
      'ru': 'Текстовое поле',
      'ta': 'உரைப்புலம்',
      'te': 'టెక్స్ట్ ఫీల్డ్',
      'th': 'ฟิลด์ข้อความ',
      'tr': 'Metin Alanı',
      'uk': 'Текстове поле',
      'vi': 'Trường văn bản',
    },
    'uhpushpb': {
      'en': 'Rest Between Cycles',
      'ar': 'الراحة بين الدورات',
      'bn': 'চক্রের মধ্যে বিশ্রাম',
      'de': 'Ruhe zwischen den Zyklen',
      'es': 'Descanso entre ciclos',
      'fr': 'Repos entre les cycles',
      'hi': 'चक्रों के बीच आराम',
      'id': 'Istirahat Antar Siklus',
      'it': 'Riposo tra i cicli',
      'ja': 'サイクル間の休憩',
      'ko': '사이클 사이의 휴식',
      'mr': 'सायकल दरम्यान विश्रांती',
      'nl': 'Rust tussen cycli',
      'pl': 'Odpoczynek między cyklami',
      'pt': 'Descanso entre os ciclos',
      'ro': 'Odihnă între cicluri',
      'ru': 'Отдых между циклами',
      'ta': 'சுழற்சிகளுக்கு இடையில் ஓய்வு',
      'te': 'చక్రాల మధ్య విశ్రాంతి',
      'th': 'พักผ่อนระหว่างรอบ',
      'tr': 'Döngüler Arası Dinlenme',
      'uk': 'Відпочинок між циклами',
      'vi': 'Nghỉ ngơi giữa các chu kỳ',
    },
    'm321gell': {
      'en': 'TextField',
      'ar': 'حقل النص',
      'bn': 'টেক্সটফিল্ড',
      'de': 'Textfeld',
      'es': 'Campo de texto',
      'fr': 'Champ de texte',
      'hi': 'पाठ्य से भरा',
      'id': 'Bidang Teks',
      'it': 'Campo di testo',
      'ja': 'テキストフィールド',
      'ko': '텍스트필드',
      'mr': 'मजकूर फील्ड',
      'nl': 'Tekstveld',
      'pl': 'Pole tekstowe',
      'pt': 'Campo de texto',
      'ro': 'Câmp de text',
      'ru': 'Текстовое поле',
      'ta': 'உரைப்புலம்',
      'te': 'టెక్స్ట్ ఫీల్డ్',
      'th': 'ฟิลด์ข้อความ',
      'tr': 'Metin Alanı',
      'uk': 'Текстове поле',
      'vi': 'Trường văn bản',
    },
    'a8pn493m': {
      'en': ':',
      'ar': ':',
      'bn': ':',
      'de': ':',
      'es': ':',
      'fr': ':',
      'hi': ':',
      'id': ':',
      'it': ':',
      'ja': '：',
      'ko': ':',
      'mr': ':',
      'nl': ':',
      'pl': ':',
      'pt': ':',
      'ro': ':',
      'ru': ':',
      'ta': ':',
      'te': ':',
      'th': '-',
      'tr': ':',
      'uk': ':',
      'vi': ':',
    },
    'o1sv0sh0': {
      'en': 'TextField',
      'ar': 'حقل النص',
      'bn': 'টেক্সটফিল্ড',
      'de': 'Textfeld',
      'es': 'Campo de texto',
      'fr': 'Champ de texte',
      'hi': 'पाठ्य से भरा',
      'id': 'Bidang Teks',
      'it': 'Campo di testo',
      'ja': 'テキストフィールド',
      'ko': '텍스트필드',
      'mr': 'मजकूर फील्ड',
      'nl': 'Tekstveld',
      'pl': 'Pole tekstowe',
      'pt': 'Campo de texto',
      'ro': 'Câmp de text',
      'ru': 'Текстовое поле',
      'ta': 'உரைப்புலம்',
      'te': 'టెక్స్ట్ ఫీల్డ్',
      'th': 'ฟิลด์ข้อความ',
      'tr': 'Metin Alanı',
      'uk': 'Текстове поле',
      'vi': 'Trường văn bản',
    },
    '5ootj27f': {
      'en': 'SAVE',
      'ar': 'يحفظ',
      'bn': 'সংরক্ষণ করুন',
      'de': 'SPEICHERN',
      'es': 'AHORRAR',
      'fr': 'SAUVEGARDER',
      'hi': 'बचाना',
      'id': 'MENYIMPAN',
      'it': 'SALVA',
      'ja': '保存',
      'ko': '구하다',
      'mr': 'जतन करा',
      'nl': 'REDDEN',
      'pl': 'RATOWAĆ',
      'pt': 'SALVAR',
      'ro': 'SALVA',
      'ru': 'СОХРАНЯТЬ',
      'ta': 'சேமி',
      'te': 'సేవ్',
      'th': 'บันทึก',
      'tr': 'KAYDETMEK',
      'uk': 'ЗБЕРЕГТИ',
      'vi': 'CỨU',
    },
    'h5dfj1n8': {
      'en': 'CANCEL',
      'ar': 'يلغي',
      'bn': 'বাতিল করুন',
      'de': 'STORNIEREN',
      'es': 'CANCELAR',
      'fr': 'ANNULER',
      'hi': 'रद्द करना',
      'id': 'MEMBATALKAN',
      'it': 'CANCELLARE',
      'ja': 'キャンセル',
      'ko': '취소',
      'mr': 'रद्द करा',
      'nl': 'ANNULEREN',
      'pl': 'ANULOWAĆ',
      'pt': 'CANCELAR',
      'ro': 'ANULA',
      'ru': 'ОТМЕНА',
      'ta': 'ரத்துசெய்',
      'te': 'రద్దు చేయి',
      'th': 'ยกเลิก',
      'tr': 'İPTAL ETMEK',
      'uk': 'СКАСУВАТИ',
      'vi': 'HỦY BỎ',
    },
    'r68alenj': {
      'en': 'Home',
      'ar': 'بيت',
      'bn': 'হোম',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'mr': 'मुखपृष्ठ',
      'nl': 'Thuis',
      'pl': 'Dom',
      'pt': 'Lar',
      'ro': 'Acasă',
      'ru': 'Дом',
      'ta': 'முகப்புப் பக்கம்',
      'te': 'హొమ్ పేజ్',
      'th': 'บ้าน',
      'tr': 'Ev',
      'uk': 'Дім',
      'vi': 'Trang chủ',
    },
  },
  // DrawerColumn
  {
    'p68mm1zg': {
      'en': 'WORKOUTS',
      'ar': 'تمارين رياضية',
      'bn': 'ওয়ার্কআউট',
      'de': 'TRAININGSPROGRAMM',
      'es': 'ENTRENAMIENTOS',
      'fr': 'ENTRAÎNEMENTS',
      'hi': 'वर्कआउट',
      'id': 'LATIHAN',
      'it': 'ALLENAMENTI',
      'ja': 'ワークアウト',
      'ko': '운동',
      'mr': 'कसरत',
      'nl': 'TRAININGEN',
      'pl': 'TRENINGI',
      'pt': 'TREINOS',
      'ro': 'ANTRENAMENTE',
      'ru': 'ТРЕНИРОВКИ',
      'ta': 'உடற்பயிற்சிகள்',
      'te': 'వ్యాయామాలు',
      'th': 'การออกกำลังกาย',
      'tr': 'ANTRENMANLAR',
      'uk': 'ТРЕНУВАННЯ',
      'vi': 'BÀI TẬP',
    },
    '9e4qxak2': {
      'en': 'AI Assistant ',
      'ar': 'مساعد الذكاء الاصطناعي',
      'bn': 'এআই সহকারী',
      'de': 'KI-Assistent',
      'es': 'Asistente de IA',
      'fr': 'Assistant IA',
      'hi': 'एआई सहायक',
      'id': 'Asisten AI',
      'it': 'Assistente AI',
      'ja': 'AIアシスタント',
      'ko': 'AI 어시스턴트',
      'mr': 'एआय असिस्टंट',
      'nl': 'AI-assistent',
      'pl': 'Asystent AI',
      'pt': 'Assistente de IA',
      'ro': 'Asistent AI',
      'ru': 'Помощник ИИ',
      'ta': 'AI உதவியாளர்',
      'te': 'AI అసిస్టెంట్',
      'th': 'ผู้ช่วย AI',
      'tr': 'Yapay Zeka Asistanı',
      'uk': 'Помічник зі штучним інтелектом',
      'vi': 'Trợ lý AI',
    },
    'rbj9dttw': {
      'en': 'temperature: ',
      'ar': 'درجة حرارة:',
      'bn': 'তাপমাত্রা:',
      'de': 'Temperatur:',
      'es': 'temperatura:',
      'fr': 'température:',
      'hi': 'तापमान:',
      'id': 'suhu:',
      'it': 'temperatura:',
      'ja': '温度：',
      'ko': '온도:',
      'mr': 'तापमान:',
      'nl': 'temperatuur:',
      'pl': 'temperatura:',
      'pt': 'temperatura:',
      'ro': 'temperatură:',
      'ru': 'температура:',
      'ta': 'வெப்பநிலை:',
      'te': 'ఉష్ణోగ్రత:',
      'th': 'อุณหภูมิ:',
      'tr': 'sıcaklık:',
      'uk': 'температура:',
      'vi': 'nhiệt độ:',
    },
    '4twnve26': {
      'en': 'topP: ',
      'ar': 'topP: ',
      'bn': 'topP: ',
      'de': 'topP:',
      'es': 'topP: ',
      'fr': 'topP: ',
      'hi': 'topP: ',
      'id': 'topP: ',
      'it': 'topP:',
      'ja': 'topP: ',
      'ko': 'topP: ',
      'mr': 'topP: ',
      'nl': 'topP:',
      'pl': 'topP: ',
      'pt': 'topP: ',
      'ro': 'topP:',
      'ru': 'topP:',
      'ta': 'topP: ',
      'te': 'topP: ',
      'th': 'topP: ',
      'tr': 'topP: ',
      'uk': 'topP: ',
      'vi': 'topP: ',
    },
    'ol7fu250': {
      'en': 'Default',
      'ar': 'تقصير',
      'bn': 'ডিফল্ট',
      'de': 'Standard',
      'es': 'Por defecto',
      'fr': 'Défaut',
      'hi': 'गलती करना',
      'id': 'Bawaan',
      'it': 'Predefinito',
      'ja': 'デフォルト',
      'ko': '기본',
      'mr': 'डीफॉल्ट',
      'nl': 'Standaard',
      'pl': 'Domyślny',
      'pt': 'Padrão',
      'ro': 'Implicit',
      'ru': 'По умолчанию',
      'ta': 'இயல்புநிலை',
      'te': 'డిఫాల్ట్',
      'th': 'ค่าเริ่มต้น',
      'tr': 'Varsayılan',
      'uk': 'За замовчуванням',
      'vi': 'Mặc định',
    },
    '2qoptgp6': {
      'en': 'settings',
      'ar': 'إعدادات',
      'bn': 'সেটিংস',
      'de': 'Einstellungen',
      'es': 'ajustes',
      'fr': 'paramètres',
      'hi': 'सेटिंग्स',
      'id': 'pengaturan',
      'it': 'impostazioni',
      'ja': '設定',
      'ko': '설정',
      'mr': 'सेटिंग्ज',
      'nl': 'instellingen',
      'pl': 'ustawienia',
      'pt': 'configurações',
      'ro': 'setări',
      'ru': 'настройки',
      'ta': 'அமைப்புகள்',
      'te': 'సెట్టింగులు',
      'th': 'การตั้งค่า',
      'tr': 'ayarlar',
      'uk': 'налаштування',
      'vi': 'cài đặt',
    },
    '141r4d0q': {
      'en': 'Properties of the generated text',
      'ar': 'خصائص النص المُولّد',
      'bn': 'তৈরি করা টেক্সটের বৈশিষ্ট্য',
      'de': 'Eigenschaften des generierten Textes',
      'es': 'Propiedades del texto generado',
      'fr': 'Propriétés du texte généré',
      'hi': 'उत्पन्न पाठ के गुण',
      'id': 'Properti teks yang dihasilkan',
      'it': 'Proprietà del testo generato',
      'ja': '生成されたテキストのプロパティ',
      'ko': '생성된 텍스트의 속성',
      'mr': 'तयार केलेल्या मजकुराचे गुणधर्म',
      'nl': 'Eigenschappen van de gegenereerde tekst',
      'pl': 'Właściwości wygenerowanego tekstu',
      'pt': 'Propriedades do texto gerado',
      'ro': 'Proprietățile textului generat',
      'ru': 'Свойства сгенерированного текста',
      'ta': 'உருவாக்கப்பட்ட உரையின் பண்புகள்',
      'te': 'రూపొందించబడిన వచనం యొక్క లక్షణాలు',
      'th': 'คุณสมบัติของข้อความที่สร้างขึ้น',
      'tr': 'Oluşturulan metnin özellikleri',
      'uk': 'Властивості згенерованого тексту',
      'vi': 'Thuộc tính của văn bản được tạo',
    },
    's7zy37pd': {
      'en': 'Styles of the generated voice',
      'ar': 'أنماط الصوت الناتج',
      'bn': 'উৎপন্ন কণ্ঠস্বরের ধরণ',
      'de': 'Stile der generierten Stimme',
      'es': 'Estilos de la voz generada',
      'fr': 'Styles de la voix générée',
      'hi': 'उत्पन्न आवाज की शैलियाँ',
      'id': 'Gaya suara yang dihasilkan',
      'it': 'Stili della voce generata',
      'ja': '生成された音声のスタイル',
      'ko': '생성된 음성의 스타일',
      'mr': 'निर्माण झालेल्या आवाजाच्या शैली',
      'nl': 'Stijlen van de gegenereerde stem',
      'pl': 'Style generowanego głosu',
      'pt': 'Estilos da voz gerada',
      'ro': 'Stiluri ale vocii generate',
      'ru': 'Стили сгенерированного голоса',
      'ta': 'உருவாக்கப்பட்ட குரலின் பாணிகள்',
      'te': 'జనరేట్ చేయబడిన వాయిస్ యొక్క శైలులు',
      'th': 'รูปแบบของเสียงที่สร้างขึ้น',
      'tr': 'Üretilen sesin stilleri',
      'uk': 'Стилі згенерованого голосу',
      'vi': 'Các phong cách của giọng nói được tạo ra',
    },
    '5x6zxzsf': {
      'en': 'Voice',
      'ar': 'صوت',
      'bn': 'কণ্ঠস্বর',
      'de': 'Stimme',
      'es': 'Voz',
      'fr': 'Voix',
      'hi': 'आवाज़',
      'id': 'Suara',
      'it': 'Voce',
      'ja': '声',
      'ko': '목소리',
      'mr': 'आवाज',
      'nl': 'Stem',
      'pl': 'Głos',
      'pt': 'Voz',
      'ro': 'Voce',
      'ru': 'Голос',
      'ta': 'குரல்',
      'te': 'వాయిస్',
      'th': 'เสียง',
      'tr': 'Ses',
      'uk': 'Голос',
      'vi': 'Tiếng nói',
    },
    'm4ksmhc2': {
      'en': 'Language',
      'ar': 'لغة',
      'bn': 'ভাষা',
      'de': 'Sprache',
      'es': 'Idioma',
      'fr': 'Langue',
      'hi': 'भाषा',
      'id': 'Bahasa',
      'it': 'Lingua',
      'ja': '言語',
      'ko': '언어',
      'mr': 'भाषा',
      'nl': 'Taal',
      'pl': 'Język',
      'pt': 'Linguagem',
      'ro': 'Limbă',
      'ru': 'Язык',
      'ta': 'மொழி',
      'te': 'భాష',
      'th': 'ภาษา',
      'tr': 'Dil',
      'uk': 'Мова',
      'vi': 'Ngôn ngữ',
    },
  },
  // VoicePickerDialog
  {
    '3ceb4s0b': {
      'en': 'Select Voice',
      'ar': 'اختر الصوت',
      'bn': 'ভয়েস নির্বাচন করুন',
      'de': 'Stimme auswählen',
      'es': 'Seleccionar voz',
      'fr': 'Sélectionner la voix',
      'hi': 'आवाज़ चुनें',
      'id': 'Pilih Suara',
      'it': 'Seleziona voce',
      'ja': '音声を選択',
      'ko': '음성 선택',
      'mr': 'आवाज निवडा',
      'nl': 'Selecteer stem',
      'pl': 'Wybierz głos',
      'pt': 'Selecione Voz',
      'ro': 'Selectați vocea',
      'ru': 'Выберите голос',
      'ta': 'குரலைத் தேர்ந்தெடுக்கவும்',
      'te': 'వాయిస్ ఎంచుకోండి',
      'th': 'เลือกเสียง',
      'tr': 'Sesi Seçin',
      'uk': 'Виберіть голос',
      'vi': 'Chọn giọng nói',
    },
  },
  // Miscellaneous
  {
    'xc0rz78e': {
      'en': 'Number of exercises',
      'ar': 'عدد التمارين',
      'bn': 'ব্যায়ামের সংখ্যা',
      'de': 'Anzahl der Übungen',
      'es': 'Número de ejercicios',
      'fr': 'Nombre d\'exercices',
      'hi': 'अभ्यासों की संख्या',
      'id': 'Jumlah latihan',
      'it': 'Numero di esercizi',
      'ja': '練習回数',
      'ko': '운동 횟수',
      'mr': 'व्यायामांची संख्या',
      'nl': 'Aantal oefeningen',
      'pl': 'Liczba ćwiczeń',
      'pt': 'Número de exercícios',
      'ro': 'Numărul de exerciții',
      'ru': 'Количество упражнений',
      'ta': 'பயிற்சிகளின் எண்ணிக்கை',
      'te': 'వ్యాయామాల సంఖ్య',
      'th': 'จำนวนครั้งของการออกกำลังกาย',
      'tr': 'Egzersiz sayısı',
      'uk': 'Кількість вправ',
      'vi': 'Số lượng bài tập',
    },
    'a61zvnsx': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    '6j13h1gz': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'k5vy8vha': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'kulkb9cv': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    '3qlgshk7': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    '9ou9is6b': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'axa8m3ae': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    '5yu4rk8w': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'ci3kreat': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    're9rba0z': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'smcdiaik': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'qo4o9jyg': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    '072wy7a0': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'snosx3fp': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'iinkl23w': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'yqj2pgpj': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    '6bqv1bbo': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'o961tp2a': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    's17emg4t': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'bnmpltys': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'haf5cxvj': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'hyqwy046': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'f2z18noq': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'arbo9rxi': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
    'yjhm29jz': {
      'en': '',
      'ar': '',
      'bn': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'mr': '',
      'nl': '',
      'pl': '',
      'pt': '',
      'ro': '',
      'ru': '',
      'ta': '',
      'te': '',
      'th': '',
      'tr': '',
      'uk': '',
      'vi': '',
    },
  },
].reduce((a, b) => a..addAll(b));
